-- Install the privileged provisioning function. The migration role owns this
-- function; inoai_sync receives only schema-scoped DML grants. With the
-- shared login role, cross-Agent isolation is enforced by the application
-- after validating AGENT_INSTANCE_ID and its derived Agent Schema.
CREATE OR REPLACE FUNCTION inoai_control.provision_agent_schema(target_schema TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, inoai_control
AS $function$
BEGIN
  IF target_schema !~ '^agent_[a-z0-9]+(?:_[a-z0-9]+)*$' OR char_length(target_schema) > 63 THEN
    RAISE EXCEPTION 'unsafe Agent Schema name: %', target_schema;
  END IF;

  EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', target_schema);

  EXECUTE format($sql$
    CREATE TABLE IF NOT EXISTS %1$I.users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      transport TEXT NOT NULL,
      workspace_id TEXT NOT NULL,
      external_user_id TEXT NOT NULL,
      display_name TEXT,
      role TEXT NOT NULL DEFAULT 'family' CHECK (role IN ('owner', 'family')),
      state TEXT NOT NULL DEFAULT 'active' CHECK (state IN ('active', 'disabled')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      created_by TEXT NOT NULL DEFAULT 'system',
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_by TEXT NOT NULL DEFAULT 'system',
      deleted_at TIMESTAMPTZ,
      deleted_by TEXT,
      CHECK ((deleted_at IS NULL AND deleted_by IS NULL) OR (deleted_at IS NOT NULL AND deleted_by IS NOT NULL)),
      UNIQUE (transport, workspace_id, external_user_id)
    );

    CREATE TABLE IF NOT EXISTS %1$I.sessions (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES %1$I.users(id),
      transport TEXT NOT NULL,
      workspace_id TEXT NOT NULL,
      parent_conversation_id TEXT NOT NULL,
      conversation_id TEXT NOT NULL,
      initiating_external_message_id TEXT NOT NULL,
      agent_provider TEXT NOT NULL,
      agent_session_id TEXT NOT NULL,
      project_path TEXT NOT NULL,
      state TEXT NOT NULL DEFAULT 'active' CHECK (state IN ('active', 'ended', 'failed')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      created_by TEXT NOT NULL DEFAULT 'system',
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_by TEXT NOT NULL DEFAULT 'system',
      ended_at TIMESTAMPTZ,
      deleted_at TIMESTAMPTZ,
      deleted_by TEXT,
      CHECK ((deleted_at IS NULL AND deleted_by IS NULL) OR (deleted_at IS NOT NULL AND deleted_by IS NOT NULL))
    );

    CREATE TABLE IF NOT EXISTS %1$I.messages (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      session_id BIGINT NOT NULL REFERENCES %1$I.sessions(id),
      transport TEXT NOT NULL,
      workspace_id TEXT NOT NULL,
      external_message_id TEXT,
      external_author_id TEXT,
      user_id BIGINT REFERENCES %1$I.users(id),
      direction TEXT NOT NULL CHECK (direction IN ('user', 'agent')),
      body TEXT NOT NULL,
      reply_to_external_message_id TEXT,
      in_reply_to_message_id BIGINT REFERENCES %1$I.messages(id),
      state TEXT NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'processing', 'completed', 'failed')),
      failure_detail TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      created_by TEXT NOT NULL DEFAULT 'system',
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_by TEXT NOT NULL DEFAULT 'system',
      started_at TIMESTAMPTZ,
      runtime_started_at TIMESTAMPTZ,
      completed_at TIMESTAMPTZ,
      provisional_id TEXT UNIQUE,
      delivery_state TEXT CHECK (delivery_state IN ('pending', 'uncertain', 'confirmed', 'failed')),
      deleted_at TIMESTAMPTZ,
      deleted_by TEXT,
      CHECK (direction != 'user' OR external_message_id IS NOT NULL),
      CHECK ((deleted_at IS NULL AND deleted_by IS NULL) OR (deleted_at IS NOT NULL AND deleted_by IS NOT NULL))
    );

    CREATE TABLE IF NOT EXISTS %1$I.events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      session_id BIGINT REFERENCES %1$I.sessions(id),
      message_id BIGINT REFERENCES %1$I.messages(id),
      event_type TEXT NOT NULL,
      detail TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      created_by TEXT NOT NULL DEFAULT 'system',
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_by TEXT NOT NULL DEFAULT 'system',
      deleted_at TIMESTAMPTZ,
      deleted_by TEXT,
      CHECK ((deleted_at IS NULL AND deleted_by IS NULL) OR (deleted_at IS NOT NULL AND deleted_by IS NOT NULL))
    );

    CREATE TABLE IF NOT EXISTS %1$I.approvals (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      session_id BIGINT NOT NULL REFERENCES %1$I.sessions(id),
      runtime_approval_id TEXT NOT NULL UNIQUE,
      request_message_id BIGINT REFERENCES %1$I.messages(id),
      resolution_message_id BIGINT REFERENCES %1$I.messages(id),
      summary TEXT NOT NULL,
      expires_at TIMESTAMPTZ NOT NULL,
      state TEXT NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'approved', 'rejected', 'expired', 'failed')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      created_by TEXT NOT NULL DEFAULT 'system',
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_by TEXT NOT NULL DEFAULT 'system',
      deleted_at TIMESTAMPTZ,
      deleted_by TEXT,
      CHECK ((deleted_at IS NULL AND deleted_by IS NULL) OR (deleted_at IS NOT NULL AND deleted_by IS NOT NULL))
    );

    CREATE TABLE IF NOT EXISTS %1$I.memory_reviews (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      session_id BIGINT NOT NULL REFERENCES %1$I.sessions(id),
      from_message_id BIGINT NOT NULL REFERENCES %1$I.messages(id),
      through_message_id BIGINT NOT NULL REFERENCES %1$I.messages(id),
      state TEXT NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'processing', 'completed', 'failed')),
      attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
      next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      recap TEXT,
      failure_detail TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      created_by TEXT NOT NULL DEFAULT 'system',
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_by TEXT NOT NULL DEFAULT 'system',
      started_at TIMESTAMPTZ,
      completed_at TIMESTAMPTZ,
      deleted_at TIMESTAMPTZ,
      deleted_by TEXT,
      CHECK ((deleted_at IS NULL AND deleted_by IS NULL) OR (deleted_at IS NOT NULL AND deleted_by IS NOT NULL))
    );

    CREATE TABLE IF NOT EXISTS %1$I.memories (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      body TEXT NOT NULL,
      source_message_id BIGINT REFERENCES %1$I.messages(id),
      created_by_user_id BIGINT REFERENCES %1$I.users(id),
      review_id BIGINT REFERENCES %1$I.memory_reviews(id),
      origin TEXT NOT NULL CHECK (origin IN ('manual', 'review')),
      state TEXT NOT NULL DEFAULT 'active' CHECK (state IN ('active', 'deleted')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      created_by TEXT NOT NULL DEFAULT 'system',
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_by TEXT NOT NULL DEFAULT 'system',
      deleted_at TIMESTAMPTZ,
      deleted_by TEXT,
      CHECK ((deleted_at IS NULL AND deleted_by IS NULL) OR (deleted_at IS NOT NULL AND deleted_by IS NOT NULL))
    );

    CREATE UNIQUE INDEX IF NOT EXISTS one_active_session_per_conversation
      ON %1$I.sessions (transport, workspace_id, conversation_id)
      WHERE state = 'active' AND deleted_at IS NULL;
    CREATE UNIQUE INDEX IF NOT EXISTS unique_initiating_message
      ON %1$I.sessions (transport, workspace_id, initiating_external_message_id);
    CREATE UNIQUE INDEX IF NOT EXISTS unique_agent_session
      ON %1$I.sessions (agent_provider, agent_session_id);
    CREATE UNIQUE INDEX IF NOT EXISTS unique_external_message
      ON %1$I.messages (transport, workspace_id, external_message_id)
      WHERE external_message_id IS NOT NULL;
    CREATE INDEX IF NOT EXISTS pending_user_messages
      ON %1$I.messages (direction, state, id)
      WHERE deleted_at IS NULL;
    CREATE INDEX IF NOT EXISTS messages_by_session
      ON %1$I.messages (session_id, id);
    CREATE INDEX IF NOT EXISTS events_by_session
      ON %1$I.events (session_id, id);
    CREATE INDEX IF NOT EXISTS pending_approvals_by_session
      ON %1$I.approvals (session_id, id)
      WHERE state = 'pending' AND deleted_at IS NULL;
    CREATE INDEX IF NOT EXISTS due_memory_reviews
      ON %1$I.memory_reviews (state, next_attempt_at, id)
      WHERE deleted_at IS NULL;
    CREATE INDEX IF NOT EXISTS active_memories
      ON %1$I.memories (state, id)
      WHERE deleted_at IS NULL;
    CREATE INDEX IF NOT EXISTS sessions_updated_at
      ON %1$I.sessions (updated_at, id);
    CREATE INDEX IF NOT EXISTS messages_updated_at
      ON %1$I.messages (updated_at, id);
    CREATE INDEX IF NOT EXISTS memories_updated_at
      ON %1$I.memories (updated_at, id);
    CREATE INDEX IF NOT EXISTS reviews_updated_at
      ON %1$I.memory_reviews (updated_at, id);
    CREATE INDEX IF NOT EXISTS events_updated_at
      ON %1$I.events (updated_at, id);
  $sql$, target_schema);

  EXECUTE format('GRANT USAGE ON SCHEMA %I TO inoai_sync', target_schema);
  EXECUTE format('GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA %I TO inoai_sync', target_schema);
  EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO inoai_sync', target_schema);
END;
$function$;

REVOKE ALL ON FUNCTION inoai_control.provision_agent_schema(TEXT) FROM PUBLIC;
